### ISSUE TITLE
Won't Build

### ISSUE THREAD

**Issue by jchisholm59** [circuitdojo/air-quality-wing-code#1]
CanaryExample.ino: In function 'void setup()':
CanaryExample.ino:109:3: error: narrowing conversion of '90' from 'int' to 'bool' [-Wnarrowing]
  109 |   };
      |   ^
make[2]: *** [../build/target/user/platform-12-mCanaryExample.o] Error 1
make[2]: Leaving directory `/firmware/user'
make[1]: *** [user] Error 2
make[1]: Leaving directory `/firmware/modules/argon/user-part'
make: *** [modules/argon/user-part] Error 2
---------------------------------------------------------------------------------------------------------------------------------------

Same error regardless of the platform .
Argon build (any version ) fails on the Web IDE, Particle Workshop, or the CLI.

**Comment by jaredwolff** [comment]
Pull the latest according to the instructions here.

https://docs.jaredwolff.com/air-quality-wing/arduino-examples.html

Working as of right now with a Boron. Xenon is no long supported. Argon should work though.
