### ISSUE TITLE
aqw won't build on argon

### ISSUE THREAD

**Issue by patcardin** [circuitdojo/air-quality-wing-code#2]
I have to say that I'm a newbie in this field, so maybe I'm doing something wrong but I cannot build using particule workbench in VS using 3.1.0 and did all the steps from here https://github.com/circuitdojo/air-quality-wing-code
here's my errors:
 
 *  Executing task: make -f '/Users/pat/.particle/toolchains/buildscripts/1.10.0/Makefile' compile-all -s 

:::: COMPILING APPLICATION & DEVICE OS

  /Users/pat/.particle/toolchains/deviceOS/3.1.0/modules/argon/system-part1/makefile /Users/pat/.particle/toolchains/deviceOS/3.1.0/modules/argon/user-part/makefile
   text    data     bss     dec     hex filename
 444840    2550   60232  507622   7bee6 ../../../build/target/system-part1/platform-12-m/system-part1.elf
Creating /Users/pat/repo/asd2/air-quality-wing-code/target/3.1.0/argon/platform_user_ram.ld ...
In file included from /Users/pat/repo/asd2/air-quality-wing-code/src/AirQualityWing.ino:9:
/Users/pat/repo/asd2/air-quality-wing-code/lib/AirQualityWing/src/AirQualityWing.h:6:21: warning: "PLATFORM_XENON" is not defined, evaluates to 0 [-Wundef]
    6 | #if (PLATFORM_ID != PLATFORM_XENON) && (PLATFORM_ID != PLATFORM_ARGON) && (PLATFORM_ID != PLATFORM_BORON)
      |                     ^~~~~~~~~~~~~~
/Users/pat/repo/asd2/air-quality-wing-code/src/AirQualityWing.ino: In function 'void loop()':
/Users/pat/repo/asd2/air-quality-wing-code/src/AirQualityWing.ino:80:10: error: 'shtc3_error' was not declared in this scope; did you mean 'strerror'?
   80 |     case shtc3_error:
      |          ^~~~~~~~~~~
      |          strerror
/Users/pat/repo/asd2/air-quality-wing-code/src/AirQualityWing.ino:86:10: error: 'sgp40_error' was not declared in this scope
   86 |     case sgp40_error:
      |          ^~~~~~~~~~~
make[3]: *** [../build/target/user/platform-12-m/air-quality-wing-code/src/AirQualityWing.o] Error 1
make[2]: *** [user] Error 2
make[1]: *** [/Users/pat/.particle/toolchains/deviceOS/3.1.0/modules/argon/user-part/makefile] Error 2
make: *** [compile-all] Error 2

 *  The terminal process "/bin/bash '-c', 'make -f '/Users/pat/.particle/toolchains/buildscripts/1.10.0/Makefile' compile-all -s'" terminated with exit code: 2. 
 *  Press any key to close the terminal.

**Comment by patcardin** [comment]
I Had to reset my ARgon board and flash it from the cloud using 3.1.0 since the cloud had been configured to auto-push new updates. problem solved!

**Comment by jaredwolff** [comment]
Awesome!! I'm going to close this out then. Feel free to re-open or create a new issue if need be.
